# Generated by Django 3.2.13 on 2022-05-07 12:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Instance's unique identifier.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When was the instance created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When was the instance updated.",
                        verbose_name="Updated At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hall",
                "verbose_name_plural": "Halls",
                "db_table": "hall",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Instance's unique identifier.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When was the instance created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When was the instance updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("COMPLETED", "Completed")],
                        default="OPEN",
                        help_text="Reservation's current status.",
                        max_length=9,
                        verbose_name="Status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="When does the reservation expire if it hasn't been completed.",
                        verbose_name="Expires At",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "db_table": "reservation",
            },
        ),
        migrations.CreateModel(
            name="Showtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Instance's unique identifier.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When was the instance created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When was the instance updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "time_showing",
                    models.DateTimeField(
                        help_text="When is the movie showing.",
                        verbose_name="Time Showing",
                    ),
                ),
                (
                    "movie_format",
                    models.CharField(
                        choices=[("2D", "2D"), ("3D", "3D"), ("4DX", "4DX")],
                        default="2D",
                        help_text="Format in which the movie is showing.",
                        max_length=3,
                        verbose_name="Movie Format",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        help_text="Hall where the movie is showing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showtimes",
                        to="reservations.hall",
                        verbose_name="Hall",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        help_text="Movie that is showing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showtimes",
                        to="movies.movie",
                        verbose_name="Movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Showtime",
                "verbose_name_plural": "Showtimes",
                "db_table": "showtime",
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Instance's unique identifier.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When was the instance created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When was the instance updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        help_text="Hall where the seat is located.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="reservations.hall",
                        verbose_name="Hall",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seat",
                "verbose_name_plural": "Seats",
                "db_table": "seat",
            },
        ),
        migrations.CreateModel(
            name="ReservationSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Instance's unique identifier.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When was the instance created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When was the instance updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        help_text="Reservation which the seat belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_seats",
                        to="reservations.reservation",
                        verbose_name="Reservation",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        help_text="Seat which is reserved.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_seats",
                        to="reservations.seat",
                        verbose_name="Seat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Seat",
                "verbose_name_plural": "Reservation Seats",
                "db_table": "reservation_seat",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="seats",
            field=models.ManyToManyField(
                help_text="Seats reserved with this reservation.",
                related_name="reservations",
                through="reservations.ReservationSeat",
                to="reservations.Seat",
                verbose_name="Seats",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="showtime",
            field=models.ForeignKey(
                help_text="Showtime for which the reservation was created.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservations.showtime",
                verbose_name="Showtime",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                help_text="User who made the reservation.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
