# Generated by Django 3.2.13 on 2022-05-07 12:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Instance's unique identifier.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When was the instance created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When was the instance updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the movie.",
                        max_length=128,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of the movie.",
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "db_table": "movie",
            },
        ),
    ]
